language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database estateManagement;' -U postgres
  - psql -c "CREATE USER testUser WITH PASSWORD 'testUser';" -U postgres
  - psql -c GRANT ALL PRIVILEGES ON DATABASE estateManagement TO testUser;
  - npm install -g sequelize-cli