language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database estateManagement;' -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
  - psql -c "ALTER ROLE test CREATEROLE CREATEDB;" -U postgres
  # - npm install -g sequelize-cli